name: upsy
channels:
  - conda-forge
dependencies:
  # Core python
  - python=3.12
  - numpy=2.4.3
  - netcdf4=1.7.4

  # Stuff to compile models
  - openmpi=5.0.10
  - petsc=3.25.1
  - netcdf-fortran=4.6.2
  - libnetcdf=4.10.0

  - gfortran
  - compilers
  - cmake
  - ninja
