name: upsy
channels:
  - conda-forge
dependencies:
  - python=3.12
  - cartopy
  - cmocean
  - dask
  - geopandas
  - matplotlib
  - netcdf4=1.7.4
  - numpy=2.4.4
  - pandas
  - pyproj
  - pyshp
  - scipy
  - shapely
  - xarray 
  - pip
  - setuptools >=61
  - tqdm
  - ipython
  - ipykernel
  - qt6-wayland
