# The full LADDIE Test Suite

name: LADDIE Test Suite
run-name: ${{ github.actor }} - LADDIE Test Suite
on:
  pull_request:
    branches:
      - main
    paths:
      - 'src/LADDIE/**'
  workflow_dispatch:

jobs:

  # Compile the model and cache the executable
  # compile_and_cache_LADDIE_dev_MacOS:
  #   uses: ./.github/workflows/LADDIE_test_suite_compile_and_cache_dev_MacOS.yml

  compile_and_cache_LADDIE_perf_MacOS:
    uses: ./.github/workflows/LADDIE_test_suite_compile_and_cache_perf_MacOS.yml

  compile_and_cache_LADDIE_dev_MacOS:
    uses: ./.github/workflows/LADDIE_test_suite_compile_and_cache_dev_MacOS.yml

  # Install and cache Python
  # install_and_cache_Python:
  #  uses: ./.github/workflows/LADDIE_test_suite_install_and_cache_Python.yml

  # Run the unit tests and analyse the results
  run_unit_tests:
    needs: compile_and_cache_LADDIE_dev_MacOS
    uses: ./.github/workflows/LADDIE_test_suite_run_unit_tests.yml

  # Run the integrated tests and analyse the results
  run_integrated_tests:
    needs: compile_and_cache_LADDIE_perf_MacOS
    uses: ./.github/workflows/LADDIE_test_suite_run_and_analyse_integrated_tests.yml
