name: UPSY Test Suite - run unit tests (performance build, Linux)
run-name: ${{ github.actor }} - UPSY Test Suite - run unit tests (performance build, Linux)
on:
  workflow_call:

jobs:
  run_unit_tests:
    runs-on: ubuntu-latest
    steps:

      - name: Set up Homebrew
        id: set-up-homebrew
        uses: Homebrew/actions/setup-homebrew@main

      - name: Install packages with Homebrew   # Packages end up in /opt/homebrew/Cellar
        run: |
          brew update
          brew install open-mpi
          brew install netcdf
          brew install netcdf-fortran
          brew unlink hdf5
          brew install petsc
          brew install cmake
          brew install ninja

      - name: Check out repository
        uses: actions/checkout@v4

      - name: Restore UPSY unit test program from cache
        uses: actions/cache/restore@v3
        id: UPSY_unit_test_program_cache_restore
        with:
          path: UPSY_unit_test_program
          key: UPSY_unit_test_program_perf_Linux_${{ github.ref_name }}_${{ github.run_id }}

      - name: Restore UPSY multi-node unit test program from cache
        uses: actions/cache/restore@v3
        id: UPSY_multinode_unit_test_program_cache_restore
        with:
          path: UPSY_multinode_unit_test_program
          key: UPSY_multinode_unit_test_program_perf_Linux_${{ github.ref_name }}_${{ github.run_id }}

      - name: Run unit tests
        run: mpiexec  -n 2  UPSY_unit_test_program

      - name: Run multi-node unit tests
        run: mpiexec  -n 7 --map-by :OVERSUBSCRIBE  UPSY_multinode_unit_test_program

      - name: Upload output as artifacts
        uses: actions/upload-artifact@v4.3.4
        with:
          name: results_unit_tests_perf_Linux
          path: automated_testing/unit_tests/results
