name: UPSY Test Suite - compiling
run-name: ${{ github.actor }} - compiling
on:
  workflow_call:

jobs:
  compile_UPSY:
    name: ${{ matrix.os }}-${{ matrix.build_type }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [macos-latest, ubuntu-latest]
        build_type: [dev, perf]
    steps:

    # Install all required packages and compile the code
    # ==================================================

      - name: Install csh (ubuntu)
        if: matrix.os == 'ubuntu-latest'
        run: |
          sudo apt-get update
          sudo apt-get install csh

      - name: Check out repository
        uses: actions/checkout@v4

      - name: Update submodules
        run: |
          git submodule update --init --remote

      - name: Set up micromamba environment
        uses: mamba-org/setup-micromamba@v2
        with:
          environment-file: environment-ci.yml
          environment-name: upsy
          cache-environment: true
          cache-downloads: true

      - name: Verify compiler setup
        shell: micromamba-shell {0}
        run: gfortran --version

      - name: Compile UFEMISM
        shell: micromamba-shell {0}
        run: csh compile_UFEMISM.csh  dev  clean

      - name: Compile UPSY
        shell: micromamba-shell {0}
        run: csh compile_UPSY.csh  ${{ matrix.build_type }}  clean

      - name: Verify compiling
        shell: micromamba-shell {0}
        run: csh automated_testing/check_if_UPSY_programs_exist.csh
