# The UPSY component tests

name: UPSY component tests
run-name: ${{ github.actor }} - UPSY component tests
on:
  pull_request:
    branches:
      - main
    paths:
      - 'src/UPSY/**'
  workflow_dispatch:

jobs:

  # Run the individual component tests in parallel as separate workflows
  mesh_creation:
    uses: ./.github/workflows/UPSY_component_test_mesh_creation.yml

  mesh_focussing:
    uses: ./.github/workflows/UPSY_component_test_mesh_focussing.yml

  mesh_discretisation:
    uses: ./.github/workflows/UPSY_component_test_mesh_discretisation.yml

  mesh_remapping_mesh_grid:
    uses: ./.github/workflows/UPSY_component_test_mesh_remapping_mesh_grid.yml
