# The full UPSY Test Suite

name: UPSY Test Suite
run-name: ${{ github.actor }} - UPSY Test Suite
on:
  pull_request:
    branches:
      - main
    paths:
      - 'src/UPSY/**'
  workflow_dispatch:

jobs:

  # Compile the model and cache the executable
  compile_and_cache_UPSY_dev_MacOS:
    uses: ./.github/workflows/UPSY_test_suite_compile_and_cache_dev_MacOS.yml

  compile_and_cache_UPSY_dev_Linux:
    uses: ./.github/workflows/UPSY_test_suite_compile_and_cache_dev_Linux.yml

  compile_and_cache_UPSY_perf_MacOS:
    uses: ./.github/workflows/UPSY_test_suite_compile_and_cache_perf_MacOS.yml

  compile_and_cache_UPSY_perf_Linux:
    uses: ./.github/workflows/UPSY_test_suite_compile_and_cache_perf_Linux.yml

  # Run the individual tests in parallel as separate workflows
  unit_tests:
    uses: ./.github/workflows/UPSY_unit_tests.yml

  mesh_creation:
    uses: ./.github/workflows/UPSY_component_test_mesh_creation.yml

  mesh_focussing:
    uses: ./.github/workflows/UPSY_component_test_mesh_focussing.yml

  mesh_discretisation:
    uses: ./.github/workflows/UPSY_component_test_mesh_discretisation.yml

  mesh_remapping_mesh_grid:
    uses: ./.github/workflows/UPSY_component_test_mesh_remapping_mesh_grid.yml

  mesh_remapping_mesh_mesh:
    uses: ./.github/workflows/UPSY_component_test_mesh_remapping_mesh_mesh.yml

