# The full UPSY Test Suite

name: UPSY Test Suite
run-name: ${{ github.actor }} - UPSY Test Suite
on:
  pull_request:
    branches:
      - main
    paths:
      - 'src/UPSY/**'
  workflow_dispatch:

jobs:

  # Run the individual tests in parallel as separate workflows
  compile_UPSY:
    uses: ./.github/workflows/UPSY_compiling.yml

  unit_tests:
    uses: ./.github/workflows/UPSY_unit_tests.yml

  mesh_creation:
    uses: ./.github/workflows/UFE_run_and_check_test.yml
    with:
      test_path: automated_testing/UPSY/component_test_mesh_creation

  mesh_focussing:
    uses: ./.github/workflows/UFE_run_and_check_test.yml
    with:
      test_path: automated_testing/UPSY/component_test_mesh_focussing

  mesh_discretisation:
    uses: ./.github/workflows/UFE_run_and_check_test.yml
    with:
      test_path: automated_testing/UPSY/component_test_mesh_discretisation

  mesh_remapping_mesh_grid:
    uses: ./.github/workflows/UFE_run_and_check_test.yml
    with:
      test_path: automated_testing/UPSY/component_test_mesh_remapping_mesh_grid

  mesh_remapping_mesh_mesh:
    uses: ./.github/workflows/UFE_run_and_check_test.yml
    with:
      test_path: automated_testing/UPSY/component_test_mesh_remapping_mesh_mesh
