name: UPSY Test Suite - run component tests (performance build, Linux)
run-name: ${{ github.actor }} - UPSY Test Suite - run component tests (performance build, Linux)
on:
  workflow_call:

jobs:
  run_component_tests:
    runs-on: ubuntu-latest
    steps:

      - name: Set up Homebrew
        id: set-up-homebrew
        uses: Homebrew/actions/setup-homebrew@main

      - name: Install packages with Homebrew   # Packages end up in /opt/homebrew/Cellar
        run: |
          brew update
          brew install open-mpi
          brew install netcdf
          brew install netcdf-fortran
          brew unlink hdf5
          brew install petsc
          brew install cmake
          brew install ninja

      - name: Check out repository
        uses: actions/checkout@v4

      - name: Restore UPSY program from cache
        uses: actions/cache/restore@v3
        id: UPSY_program_cache_restore
        with:
          path: UPSY_component_test_program
          key: UPSY_component_test_program_perf_Linux_${{ github.ref_name }}_${{ github.run_id }}

      - name: Run component tests
        run: mpiexec  -n 2  UPSY_component_test_program

      # - name: Run multi-node component tests
      #   run: mpiexec  -n 7 --map-by :OVERSUBSCRIBE  UPSY_component_test_program  component_tests_multinode

      - name: Upload output as artifacts
        uses: actions/upload-artifact@v4.3.4
        with:
          name: results_component_tests_perf_Linux
          path: automated_testing/component_tests/results
